# This file was generated by GoReleaser. DO NOT EDIT.
cask "modjo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "72b00d9d6592170dd2954ab99ff108a9954472e38cbc2e9c40dffa2e1f23480a"
      url "https://github.com/tdeschamps/modjo-cli/releases/download/v#{version}/modjo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5c0965fd9642c3c83e45c8b07c87f2fcb753a6b39aa6fb3ac7a00dee859b905"
      url "https://github.com/tdeschamps/modjo-cli/releases/download/v#{version}/modjo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b4f8f00e743d9aeb940154d6dde7bf346a23fb3527ac9c3a2580228f6a112b0"
      url "https://github.com/tdeschamps/modjo-cli/releases/download/v#{version}/modjo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b0c90de155e85ad16f9ce1e021dcc9c35104794a11654d12424dacc63d9537a"
      url "https://github.com/tdeschamps/modjo-cli/releases/download/v#{version}/modjo_linux_arm64.tar.gz"
    end
  end

  name "modjo"
  desc "Script the Modjo API and drive it with natural language"
  homepage "https://github.com/tdeschamps/modjo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "modjo"

  # No zap stanza required

end
