# This file was generated by GoReleaser. DO NOT EDIT.
cask "opusclip" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f998bc6ff98c34bdcd5edbf02c06437bf48ef20eb4d60c35024de965265bad5b"
      url "https://github.com/tdeschamps/opusclip-cli/releases/download/v#{version}/opusclip_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10b211927e16f0fc4f8c59aa45590e168381f4f9e92352ebfc2bb5b392edae4d"
      url "https://github.com/tdeschamps/opusclip-cli/releases/download/v#{version}/opusclip_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f5265c7d884adf1972d158369d8a87492eb4776a45240fc4bccbdc5552dba68"
      url "https://github.com/tdeschamps/opusclip-cli/releases/download/v#{version}/opusclip_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "408e1cba999726b4aaaccb0379cf2510bc586d99cbd6b8d40bde2ac3c6f01da1"
      url "https://github.com/tdeschamps/opusclip-cli/releases/download/v#{version}/opusclip_linux_arm64.tar.gz"
    end
  end

  name "opusclip"
  desc "Turn long videos into short clips from the command line"
  homepage "https://github.com/tdeschamps/opusclip-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opusclip"

  # No zap stanza required

end
